# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkk',
            name='area_type',
            field=models.IntegerField(default=1, verbose_name='\u0422\u0438\u043f \u0443\u0447\u0430\u0441\u0442\u043a\u0430'),
        ),
    ]
