# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkk', '0002_pkk_area_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkk',
            name='image_version',
            field=models.IntegerField(default=1, verbose_name='\u0412\u0435\u0440\u0441\u0438\u044f \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f'),
        ),
    ]
